Para fines de verificación de Términos y Condiciones de Servicio Vigentes, el solicitante está asumiendo que se encuentra en perfecto uso de sus facultades mentales y en condiciones para aceptar y aprobar dicho inicio de solicitud de consultoría y apoyo para la gestión de su Visado Americano y su tramite DS-160.

Considere que el formato actual está predispuesto en base a los Términos y Condiciones de Servicio vigentes, el servicio es considerado posterior a la aceptación de términos y condiciones, una vez que el usuario proporciona la información correspondiente al formato vigente y designado por el sitio: " www.visasolicitud.com ". Considere que dicha información se usara solo con fines únicos y exclusivamente para el llenado del Formato DS-160 y agendar citas correspondientes en CAS (Centro de Atención al Solicitante). También considere que su Status actual no reflejara ningún movimiento hasta hacer previa notificación en el sitio: " www.visasolicitud.com/notificar " posteriormente haber enviado el ticket de pago y el formato DS-160 resuelto a: "pagos@visasolicitud.com", con el fin de corroborar el Status de Pago y hacerle la notificación automática al correo que señale para el requerimiento y presentación de datos que se puedan requerir en base al tramitador. El Status de pago no cambiara hasta presentar todo lo señalado posterior a la notificación.
Para todos los fines de consulta de Status hasta recibir la notificación del formato DS-160 y la generación de Usuario para Agendar Citas en el CAS, se considerará el sitio: " www.visasolicitud.com/login " (con su único usuario previo al que señalo en su registro) y en base a realizar el pago solicitado el solicitante acepta dichas disposiciones del sitio y los términos vigentes.

TÉRMINOS Y CONDICIONES

Estos términos y condiciones, tiene por objeto reglamentar la contratación del servicio que se está solicitando por medio de la página www.visasolicitud.com aceptando que este sitio NO es el oficial y que no tiene ningún vínculo con la embajada ni consulado americano.
El usuario está de acuerdo que este sitio funge como servicio de gestión legal única y exclusivamente para gestionarle su tramite DS-160-.
Si bien es cierto, que nuestro propio pacto federal establece leyes, reglas y procedimientos para llevar a cabo la contratación de un servicio, por tal razón en este documento se plasman las cláusulas y aclaraciones correspondientes para ambas partes, en el cual se especifican los detalles. Por tal motivo es importante que el solicitante lea siempre dichos temimos, ya que la empresa dará por asentado que el cliente los leyó y por consecuencia está de acuerdo en dicho servicio. Es importante que el solicitante tenga la tranquilidad de proporcionar sus datos personales, ya que la empresa se encuentra totalmente en apego a La Ley Federal de Protección de Datos Personales en Posesión de Particulares, la cual es un cuerpo normativo de México, aprobado por el Congreso de la Unión el 27 de abril de 2010, mismo que tiene como objetivo regular el derecho a la autodeterminación informativa. Esta Ley fue publicada el 5 de julio de 2010 en el Diario Oficial de la Federación y entró en vigor el 6 de julio de 2010. Sus disposiciones son aplicables a todas las personas físicas o morales que lleven a cabo el tratamiento de datos personales en el ejercicio de sus actividades, por lo tanto, empresas como bancos, aseguradoras, hospitales, escuelas, compañías de telecomunicaciones, asociaciones religiosas, y profesionistas como abogados, médicos, entre otros, se encuentran obligados a cumplir con lo que establece esta ley. LFPD Ley Federal de Protección de Datos

1. Para los efectos de dichos términos se entiende por:
I. Página web www.visasolicitud.com : página de internet en la cual se ofrece un servicio al solicitante, con el fin de ayudarle a realizar la solicitud de visa americana. II. Solicitante: persona física, que está solicitando un servicio, referente a la solicitud de tramitación de la visa americana. III. Servicio: asistencia que se le otorga al solicitante cuando lo solicita por medio de la página y a su vez ha llevado acabo su pago correspondiente. Dicho servicio tiene como objeto realizar la solicitud de la visa americana, por medio de los datos que el solicitante proporcione a través de un formato. IV. Formato: documento que contiene la información necesaria del solicitante para llevar a cabo la solicitud V. Pago: pago monetario que se realiza por parte del solicitante para poder brindarle el servicio. VI. Tramite: servicio que se realiza con el fin de solicitar la visa americana. VII. Datos personales: información personal del solicitante que se utilizaran única y exclusivamente para realizar la solicitud del trámite de visa.
Proceso del servicio:
El primer contacto se realiza cuando el solicitante ingresa a la página www.visasolicitud.com, una vez dentro del sitio web el solicitante escoge el tipo de trámite que desea solicitar, ya sea la solicitud de trámite para una visa de renovación, por primera vez, trabajo, negocios etc. Una vez seleccionado lo anterior se le indicara al solicitante que lea los términos y condiciones y si está de acuerdo en dichos términos se le pedirá que los acepte para poder emperezar con su trámite. A continuación, se le requerirá al solicitante que complete algunos datos para la petición de solicitud en el cual se le indica si se le puede realizar dicho trámite y a su vez programar sus citas correspondientes ante la embajada, posterior se le indica el costo por el tramite o tramites que está solicitando.
Si el solicitante decide que efectivamente desea adquirir el servicio por el costo que se le indico, el siguiente paso es realizar el pago de dicho trámite en alguna de las opciones de pago que se le presentan en el sitio web, se le pide que realice dicho pago y que notifique después de realizarlo en el sitio web en el apartado de notificaciones de pago (en el caso de que el pago sea dudoso se le pedirá el Boucher o ticket de dicho pago).
Una vez realizado lo anterior mencionado, se le envía al solicitante un archivo que contiene un cuestionario, el cual se les pide que lo contesten detenidamente, que se conduzcan con la verdad, ya que dicho cuestionario es en la información en la que nos basaremos para poder realizar la solicitud de la visa ante la embajada de los Estados Unidos.
Una vez que contestaron dicho cuestionario lo envían y por consiguiente damos inicio a realizar la solicitud con el llenado de datos que nos proporcionaron ante la embajada, una vez terminado el formulario nos arroja un código directo de la embajada el cual quiere decir que podemos iniciar a abrirle al solicitante una cuenta, una vez que se generó dicha cuenta y se llenó adecuadamente con los datos del solicitante, nos permite elegir las fechas(siempre y cuando el solicitante pague el costo que la embajada designa por el tipo de visa que solicito) para que el solicitante pueda asistir a las entrevistas correspondientes ante la embajada.
Por ultimo le enviamos al correo que el solicitante nos indicó, el archivo de su registro del formulario ante la embajada junto con su clave correspondiente, también le enviamos el nombre de usuario y contraseña que les generamos para que ellos solamente ingresen y escojan los días de sus citas que sea más de su conveniencia (en dicha cuenta también se les indica la documentación que tendrán que presentar y toda la información necesaria.)

2. Clausulas
I. Dicho lo anterior es importante destacar que el solicitante acepta que somos BROKERS (que actuamos como intermediarios) por tal razón está bajo su consentimiento saber que está contratando un servicio, el cual consiste en realizar una solicitud de visa americana por medio de un trámite. II. Es necesario que el solicitante realice primero su pago, para poder empezar a realizar la solicitud DS-160 de su trámite. III. El solicitante deberá proporcionar la información que se le solicitará por medio de un formato. IV. La información que proporciona el solicitante es con la que llevaremos a cabo la solicitud del trámite de visa americana, dependerá del solicitante que tan completa proporciona dicha información, dejando claro que no nos hacemos responsables de como llene el formato ds160 el solicitante V. La información del solicitante se utilizará única y exclusivamente para para la solicitud del trámite de visa americana. VI. El pago del solicitante le incluye únicamente un servicio de solicitud para realizar el trámite de visa americana dejando claro que no incluye el costo de la visa por parte de la embajada. VII. El horario de respuesta ante una solicitud puede variar entre 24 y 72 horas hábiles y tomando en cuenta que los horarios estipulados son de 9:00am a 3:00 pm de lunes a viernes.

3. Aclaraciones
a) La empresa ofrece un servicio, en el cual realiza la solicitud de un trámite de visa americana, es importante aclarar que no somos la embajada americana ni tenemos relaciones con ellos, por lo cual nosotros no otorgamos ni garantizamos la aprobación de la visa americana.
b) El pago por el servicio de la solicitud del trámite es muy independiente al costo de la visa americana, por lo tanto, el servicio no incluye el pago que requiere la embajada del Estados Unidos de América por dicha visa, por tal razón es importante que el solicitante este consciente que acepta la condición de pago interpuesta por la gestión de su trámite en www.visasolicitud.com por la cantidad vigente de 55 USD Dólares al tipo de cambio de la divisa de Pesos Mexicanos.
Lo anterior con efecto de dejar claro que el solicitante está de acuerdo de que efectuara 2 pagos en su totalidad para poder generar las Cita(s) en el Consulado Americano. El primer pago por concepto de gestión de su trámite en base al formato DS-160 y ligarlo con el CAS y el segundo pago, siendo el solicitado por el Consulado Americano.
c) La solicitud del trámite se llevará a cabo conforme y en apego a la información que proporcione el solicitante, si dicha información es errónea, contiene falsedades o está incompleta, no nos hacemos responsable y nos deslindamos de cualquier contrariedad que esta obtenga.
d) Se designa como único medio de conducto para contacto de dudas el correo electrónico contacto@visasolicitud.com el cual estar en funcionamiento de lunes a viernes en días hábiles con un horario de 9:00 am a 3:00 pm
e) Es importante que el solicitante revise siempre todas las carpetas del correo que nos proporcionó para sus notificaciones, tales como la de correo no deseado etc., ya que no nos hacemos responsables de que nuestros correos se vayan a SPAM, de tal modo que si no las reviso y por tal motivo no vio en tiempo los correos enviados dejamos claro que no es nuestra responsabilidad y nos deslindamos para una contrariedad futura, que quisieran reclamar el solicitante.  
f) Vigencia del Trámite, serán otorgados 30 días hábiles como termino al solicitante para que proporcione toda la información que se le requiere para su formato, de no proporcionarla en termino se serrara por inconclusa su solicitud y a su vez se perderá su pago. 
g) Podrá hacer la solicitud de su trámite cualquier día de los 365 días del año, pero se dará inicio con la tramitación en días laborables los cuales son de lunes a viernes en días hábiles. 

4. Reembolsos
Bajo ninguna circunstancia fuera de lo señalado se aplicarán reembolsos. Depósitos por error, depósitos por confusión, depósitos por falta de lectura, el sitio se deslinda de responsabilidad alguna, por ello se indican los incisos previos y posteriores.
Los reembolsos NO aplican por ningún otra causa.
Cualquier reembolso estipulado por las siguientes faltas serán rechazados de forma inmediata:
- Falta de lectura y desconocer nuestro servicio.
- Confundir nuestro servicio con un visado.
- Confundir nuestro servicio con un visado seguro.
- Falta de lectura en cualquier termino y condición.
- Requerir el reembolso tajantemente por desconocer que somos un servicio de trámites.
- Deposito por confusión / desistimiento / error / ignorancia de que está contratando un servicio de trámite.
- Entre otras causas y razones que pudiera propiciar el cliente...
La única forma aplicable a un reembolso se estipula de la siguiente manera: El solicitante podrá solicitar única y exclusivamente el rembolso de su dinero en el caso de que no se haya dado inicio a su trámite durante los 15 días hábiles posteriores a la fecha en que el solicitante envió su formato contestado totalmente. (Explicación: Si usted envió ya el formato DS-160 resuelto y el ticket de su pago ó comprobante al correo de pagos@visasolicitud.com y han pasado 15 días desde entonces sin respuesta, usted podrá aplicar al reembolso de forma inmediata).
Para hacer efectivo lo anterior el solicitante tendrá que hacer la petición por medio del correo contacto@fotmatovisa.com, en el cual indicara la fecha en que envió su formato contestado de manera correcta, y tendrá que exhibir como prueba dicho correo y la fecha al día que lo está solicitando la cual deberá coincidir con los 15 días hábiles transcurridos. Es importante aclarar, que para hacer la petición de rembolso no deberán de haber transcurrido más de 35 días después de que realizo dicho pago, no se realizara ningún tipo de rembolso de no ser por la única causa que de describe en el anterior párrafo, se podrá cancelar el servicio en el momento en el que el solicitante lo pida por medio del correo, dejando claro que la petición de cancelación no es un rembolso y por consecuencia no se hará ninguna devolución de dinero. Es importante que el solicitante revise todas las carpetas de su correo como no deseado etc. Ya que no nos hacemos responsables de que nuestros correos se vayan a SPAM del correo del solicitante.
Es importante señalizar que al aplicar el reembolso su correo queda baneado de nuestro sistema, así como se dará de forma inmediata de baja de nuestra base de datos y el borrado inmediato de su información de nuestro sistema.
Si usted solicita un reembolso y es rechazado puede solicitar por su seguridad el vaneo de su correo, así como dar de baja de forma inmediata nuestra base de datos y el borrado inmediato de su información de nuestro sistema.
Considere que para cualquier preámbulo legal usted está aceptando que está recibiendo un servicio de trámite de visado por parte de visasolicitud.com y que está aceptando que no aplica ningún reembolso por ende usted accede a efectuar el pago de servicios de aquí en adelante.

5. Servicio a Proporcionarse
El solicitante está de acuerdo que una vez efectuado su pago, nosotros ya estamos proporcionándole parte del servicio por procesos de verificación. También como parte de la gestión de www.visasolicitud.com estamos de acuerdo en que se le solicitara la información correspondiente para su Formato DS-160 y ligarlo con el CAS, para que el solicitante esté en disposición de presentar la documentación que sea requerida por parte de nosotros.

6. Efectos Legales
Para dar inicio a su trámite es necesario que el solicitante acepte los términos y condiciones que se describen en dicho documento de no ser así no daremos inicio a la solicitud del trámite. 
Una vez aceptados dichos términos y condiciones damos por asentado que el solicitante está de acuerdo con todas y cada una de los términos y condiciones que se describen en dicho documento, también el solicitante está asumiendo que se encuentra en perfecto uso de sus facultades mentales y en condiciones para aceptar y aprobar dicho formato y esta consiente de que se le está proporcionando un servicio de gestión de trámite en base a la información que él nos proporcione.
Es importante destacar que nos deslindamos de cualquier contrariedad que se suscite para efectos legales, debido a que el solicitante está aceptando cada una de nuestras condiciones y a su vez nos estamos basando en los datos proporcionados por el solicitante dejando claro que no es nuestra responsabilidad que dichos datos sean erróneos o que contengan falsedades, por tal motivo nos deslindamos de cualquier responsabilidad legal que nos quieran atribuir por algún tipo de inconformidad o mal entendido. También es importante resaltar que, en el caso de una demanda, denuncia o algún trámite legal en el cual tengamos que dar seguimiento, se hará responsable a dicha persona inconformada por el pago de todos los gastos, costas y perdidas que se originen por el prejuicio que nos cause y pérdida de tiempo que se nos ocasione. Para efectos legales indicamos que deberán de tener como sede Guadalajara Jalisco.

7. Tecnología de pago
El sitio garantiza y propicia que utiliza la tecnología de pago de OpenPay. Y en su subyacente PayNet para garantizar el pago.
Recuerde que todos los pagos quedan vinculados bajo el número de pasaporte que el cliente proporcione y este pago NO es transferible a otros pasaportes o cuentas. El pago es único y valido únicamente para la referencia única de la cuenta que se liga con el pasaporte.
Para más información de la tecnología de pago puede escribir a pagos@visasolicitud.com

POLÍTICA DE PRIVACIDAD EN BASE A LA REFERENCIA EN: " www.visasolicitud.com/informacion/privacidad.php "

1. Contenido Y Aceptación De La Política De Privacidad
La presente Política de Privacidad tiene por objeto dar a conocer el modo en que recabamos, tratamos y protegemos los datos de carácter personal recabados a través del Sitio Web, a fin de que los usuarios determinen libre y voluntariamente si desean facilitar sus datos personales a través de los formularios habilitados al efecto.
El Sitio Web proporcionará a los usuarios los recursos técnicos adecuados para que, con carácter previo a la cumplimentación de los datos personales, puedan acceder a esta Política de Privacidad y a cualquier otra información relevante en materia de Protección de Datos de Carácter Personal.
El acceso y uso del Sitio Web por el usuario (el "Usuario") implica que acepta en su totalidad y se obliga a cumplir por completo los términos y condiciones recogidos en la presente Política de Privacidad, así como en las disposiciones contenidas en el Aviso Legal y Condiciones de Uso, la Política de Cookies y, en su caso, las Condiciones Generales Contratación; configurándose los citados documentos en su conjunto como los Textos Legales rectores del Sitio Web. La prestación del servicio del Sitio Web tiene una duración limitada al momento en el que el Usuario se encuentre conectado al Sitio Web o alguno de los servicios que a través del mismo se facilitan; por tanto, el Usuario debe leer atentamente la presente Política de Privacidad en cada una de las ocasiones que se proponga utilizar el Sitio Web, ya que ésta puede sufrir modificaciones en función de novedades o exigencias legislativas y jurisprudenciales o por necesidades de negocio.
La presente Política de Privacidad será válida únicamente para los datos de carácter personal obtenidos en el Sitio Web, no siendo aplicable para aquella información recabada por terceros en otras páginas web, incluso si éstas se encuentran enlazadas por el Sitio Web.

2. Todos los campos que aparezcan señalados con un asterisco (*) en dichos formularios serán de obligada cumplimentación, de tal modo que la omisión de alguno de ellos podría comportar la imposibilidad de que se pueda atender su solicitud. 
Asimismo, al hacer "clic" en el botón "Enviar" (o equivalente) incorporado en los citados formularios, declara que la información y los datos que en ellos ha facilitado son exactos y veraces. En el contexto de los tratamientos que se describen a continuación, es posible que suministre datos de carácter personal relativos a terceros. En este sentido, es su responsabilidad informar de tal circunstancia a los terceros cuyos datos nos va a ceder, así como, en caso de ser necesario, obtener su consentimiento expreso para suministrarnos dicha información.

3. Responsables De Gestionar Llamadas Al Teléfono Proporcionado
Somos responsables de cualquier llamada que se efectué al teléfono que usted proporcione con su IP en este sitio, de tal manera que esta llamada sirve con un fin informativo y dar a conocer las posibilidades para adquirir una asesoría con nosotros. Esta asesoría señalada puede implicar y recaer en costos que se señalizan previamente en nuestro sitio con el fin de proporcionar la asesoría correcta a la persona llamada.

4.Deslindar Responsabilidad Directa Con El Consulado
El sitio de VISASOLICITUD.COM, sirve de conducto para facilitar el trámite de Visa Americana, el usuario con la IP Actual: 187.193.197.24, o en su defecto con la que halla previamente adquirido el servicio acepta y confirma y deslinda cualquier responsabilidad civil, penal por cualquier circunstancia presentada ante la adquisición del servicio y pago del mismo.
